export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const GET_EXPENSES = 'GET_EXPENSES';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const GET_REPORT_WEEKLY = 'GET_REPORT_WEEKLY';
export const GET_EXPENSES_ADMIN = 'GET_EXPENSES_ADMIN';
